const movieIdeas = [
    { movie: 'Inception', food: 'Pizza', cocktail: 'Margarita' },
    { movie: 'The Shawshank Redemption', food: 'Popcorn', cocktail: 'Old Fashioned' },
    { movie: 'The Dark Knight', food: 'Nachos', cocktail: 'Cosmopolitan' },
    { movie: 'Pulp Fiction', food: 'Burgers', cocktail: 'Whiskey Sour' },
    { movie: 'Jurassic Park', food: 'Dino Nuggets', cocktail: 'Mai Tai' },
    { movie: 'Titanic', food: 'Seafood Platter', cocktail: 'Blue Lagoon' },
    { movie: 'The Godfather', food: 'Caviar', cocktail: 'Negroni' },
    { movie: 'Avatar', food: 'Mozzarella Sticks', cocktail: 'Mojito' },
    { movie: 'Forrest Gump', food: 'Chocolate', cocktail: 'White Russian' },
    { movie: 'The Silence of the Lambs', food: 'Chianti', cocktail: 'Bloody Mary' },
    { movie: 'The Avengers', food: 'Shawarma', cocktail: 'Pina Colada' },
    { movie: 'The Lion King', food: 'Hakuna Matata Platter', cocktail: 'Jungle Juice' },
    { movie: 'Gladiator', food: 'Spartan Skewers', cocktail: 'Spartan Spirit' },
    { movie: 'Casablanca', food: 'Hummus', cocktail: 'Casablanca Cooler' },
    { movie: 'The Wizard of Oz', food: 'Yellow Brick Road Mix', cocktail: 'Emerald City Elixir' },
    { movie: 'E.T. the Extra-Terrestrial', food: 'Reese\'s Pieces', cocktail: 'Galactic Goblet' },
    { movie: 'The Shawshank Redemption', food: 'Popcorn', cocktail: 'Old Fashioned' },
    { movie: 'The Matrix', food: 'Matrix Munchies', cocktail: 'Binary Bliss' },
    { movie: 'The Breakfast Club', food: 'Cereal Buffet', cocktail: 'High School Highball' },
    { movie: 'Back to the Future', food: 'Dehydrated Pizza', cocktail: 'Flux Capacitor Fizz' },
    { movie: 'Jaws', food: 'Fish and Chips', cocktail: 'Shark Bite' },
    { movie: 'Frozen', food: 'Ice Cream', cocktail: 'Frozen Fizz' },
    { movie: 'Raiders of the Lost Ark', food: 'Temple Tenders', cocktail: "Indy's Intoxication" },
    { movie: 'The Terminator', food: 'Metallic Mix', cocktail: 'Cybernetic Sip' },
    { movie: 'Blade Runner', food: 'Replicant Rolls', cocktail: 'Electric Elixir' },
    { movie: 'The Shining', food: 'Redrum Rations', cocktail: 'Overlook Old Fashioned' },
    { movie: 'The Big Lebowski', food: 'White Russian', cocktail: "The Dude's Delight" },
    { movie: 'Ghostbusters', food: 'Slimed Snacks', cocktail: 'Ecto Cooler' },
    { movie: 'Die Hard', food: 'Nakatomi Nibbles', cocktail: 'Yippee Ki-Yay Martini' },
    { movie: 'The Rocky Horror Picture Show', food: 'Time Warp Treats', cocktail: 'Rocky Rapture' },
    { movie: 'Grease', food: 'Greaser Grub', cocktail: 'Pink Lady Punch' },
    { movie: 'Memento', food: 'Memory Morsels', cocktail: 'Forget-Me-Not Fizz' },
    { movie: 'The Sixth Sense', food: 'Ghostly Gourmet', cocktail: 'Spirited Spritz' },
    { movie: 'The Departed', food: 'Undercover Udon', cocktail: 'Double Agent Daiquiri' },
    { movie: 'Black Swan', food: 'Ballet Bites', cocktail: 'Swan Lake Sangria' },
    { movie: 'The Shape of Water', food: 'Seafood Sampler', cocktail: 'Aqua Amour' },
    { movie: 'Get Out', food: 'Hypnotic Hors d\'oeuvres', cocktail: 'Mind Control Martini' },
    { movie: 'Mad Max: Fury Road', food: 'Post-Apocalyptic Platter', cocktail: 'Wasteland Whiskey' },
    { movie: 'The Revenant', food: 'Wilderness Wonders', cocktail: 'Survivor Sip' },
    { movie: 'Birdman', food: 'Broadway Bites', cocktail: 'Starstruck Sour' },
    { movie: 'The Hateful Eight', food: 'Frontier Feast', cocktail: 'Outlaw Old Fashioned' },
    { movie: 'Whiplash', food: 'Jazzed-Up Jamboree', cocktail: 'Rhythm & Rye' },
    { movie: 'Django Unchained', food: 'Wild West Wings', cocktail: 'Bounty Hunter Bourbon' },
    { movie: 'No Country for Old Men', food: 'Desert Delicacies', cocktail: 'Lone Rider Libation' },
    { movie: 'The Wolf of Wall Street', food: 'Financial Finger Foods', cocktail: 'Stockbroker Sip' },
    { movie: 'Gravity', food: 'Celestial Cuisine', cocktail: 'Zero Gravity Gimlet' },
    { movie: 'La La Land', food: 'Hollywood Hors d\'oeuvres', cocktail: 'Starstruck Spritzer' },
    { movie: 'Moonlight', food: 'Moonlit Munchies', cocktail: 'Midnight Mint Julep' },
    { movie: 'The Green Mile', food: 'Correctional Cuisine', cocktail: 'Death Row Delight' },
    { movie: 'Inglourious Basterds', food: 'War Zone Wings', cocktail: 'Tarantino Tonic' },
    { movie: 'The Great Gatsby', food: 'Gatsby Gourmet', cocktail: 'Jazz Age Julep' },
    { movie: 'The Martian', food: 'Space Survival Snacks', cocktail: 'Red Planet Refresher' },
    { movie: 'The Truman Show', food: 'Reality TV Treats', cocktail: "Truman's Tonic" },
    { movie: 'Shutter Island', food: 'Psych Ward Platter', cocktail: 'Lighthouse Libation' },
    { movie: 'A Beautiful Mind', food: 'Genius Grub', cocktail: 'Intellectual Infusion' },
    { movie: 'The Prestige', food: "Magician's Morsels", cocktail: "Illusionist's Elixir" },
    { movie: 'The King\'s Speech', food: 'Regal Repast', cocktail: "Monarch's Martini" },
    { movie: 'American Beauty', food: 'Suburban Sustenance', cocktail: "Rose's Reviver" },
    { movie: 'The Usual Suspects', food: 'Criminal Cuisine', cocktail: 'Keyser Söze Sip' },
    { movie: 'The Pianist', food: 'Piano Player Platter', cocktail: 'Melodic Martini' },
    { movie: 'Amélie', food: 'French Feast', cocktail: 'Montmartre Mule' },
    { movie: 'The Intouchables', food: 'Feel-Good Fare', cocktail: 'Heartwarming Highball' },
    { movie: 'Spirited Away', food: 'Enchanted Edibles', cocktail: 'Spirit Soother' },
    { movie: 'Eternal Sunshine of the Spotless Mind', food: 'Memory Lane Munchies', cocktail: 'Sunshine Spritz' },
    { movie: 'Her', food: 'Futuristic Feast', cocktail: 'Artificial Intelligence Appletini' },
    { movie: 'Lost in Translation', food: 'Cultural Cuisine', cocktail: 'Tokyo Twilight' },
    { movie: 'The Shape of Water', food: 'Aqua Amour', cocktail: 'Seafood Splash' },
    { movie: 'A Star is Born', food: 'Rockstar Refreshments', cocktail: 'Stardust Sip' },
    { movie: 'Bohemian Rhapsody', food: "Queen's Quarters", cocktail: "Rock n' Roll Rum" },
    { movie: 'The Joker', food: 'Villainous Victuals', cocktail: 'Chaos Cocktail' },
    { movie: 'Black Panther', food: 'Wakanda Wonders', cocktail: 'Panther Potion' },
    { movie: 'Wonder Woman', food: 'Amazonian Appetizers', cocktail: 'Lasso Libation' },
    { movie: 'Spider-Man: Into the Spider-Verse', food: 'Web-slinger Snacks', cocktail: 'Spidey Spritzer' },
    { movie: 'Avengers: Endgame', food: 'Superhero Spread', cocktail: "Avenger's Assemble Ale" },
    { movie: 'The Irishman', food: 'Mobster Munchies', cocktail: "Gangster's Gimlet" },
    { movie: 'Once Upon a Time in Hollywood', food: "Hollywood Hors d'oeuvres", cocktail: 'Tinseltown Tonic' },
    { movie: 'Parasite', food: 'Subversive Supper', cocktail: 'Class Struggle Cooler' },
];

export default movieIdeas